CREATE WAREHOUSE IF NOT EXISTS DQ_GUARDIAN_WH
  WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for the Agentic Data Quality Guardian';
USE WAREHOUSE DQ_GUARDIAN_WH;

CREATE DATABASE IF NOT EXISTS DQ_GUARDIAN
  COMMENT = 'CoCoQuest Theme 1 - Agentic Data Quality Guardian';
CREATE SCHEMA IF NOT EXISTS DQ_GUARDIAN.RAW    COMMENT = 'Source tables (with deliberate quality problems)';
CREATE SCHEMA IF NOT EXISTS DQ_GUARDIAN.CLEAN  COMMENT = 'Sandbox copies where approved fixes are applied';
CREATE SCHEMA IF NOT EXISTS DQ_GUARDIAN.DQ     COMMENT = 'Rules, scan results, fix proposals, audit log';

CREATE TABLE IF NOT EXISTS DQ_GUARDIAN.DQ.RULES (
  RULE_ID       VARCHAR NOT NULL,
  TABLE_FQN     VARCHAR NOT NULL,
  RULE_TYPE     VARCHAR,
  DIMENSION     VARCHAR,
  KIND          VARCHAR DEFAULT 'ROW',
  COLUMN_NAME   VARCHAR,
  EXPRESSION    VARCHAR,
  PARAMS        VARCHAR,
  SEVERITY      VARCHAR DEFAULT 'MEDIUM',
  DESCRIPTION   VARCHAR,
  FIX_TEMPLATE  VARCHAR,
  SOURCE        VARCHAR DEFAULT 'AUTO',
  ACTIVE        BOOLEAN DEFAULT TRUE,
  CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DQ_GUARDIAN.DQ.SCAN_RUNS (
  RUN_ID        VARCHAR,
  SOURCE_FQN    VARCHAR,
  TARGET_FQN    VARCHAR,
  PHASE         VARCHAR,
  RUN_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  RUN_BY        VARCHAR DEFAULT CURRENT_USER(),
  TOTAL_ROWS    NUMBER,
  ISSUE_ROWS    NUMBER,
  RULES_TOTAL   NUMBER,
  RULES_FAILED  NUMBER,
  HEALTH_SCORE  FLOAT,
  STRICTNESS    FLOAT,
  DIM_SCORES    VARCHAR
);

CREATE TABLE IF NOT EXISTS DQ_GUARDIAN.DQ.SCAN_RESULTS (
  RUN_ID        VARCHAR,
  RULE_ID       VARCHAR,
  RULE_TYPE     VARCHAR,
  DIMENSION     VARCHAR,
  COLUMN_NAME   VARCHAR,
  SEVERITY      VARCHAR,
  DESCRIPTION   VARCHAR,
  FAILED_ROWS   NUMBER,
  TOTAL_ROWS    NUMBER,
  PASS_PCT      FLOAT,
  STATUS        VARCHAR,
  SAMPLE_VALUES VARCHAR,
  ERROR_MSG     VARCHAR
);

CREATE TABLE IF NOT EXISTS DQ_GUARDIAN.DQ.FIX_PROPOSALS (
  PROPOSAL_ID   VARCHAR,
  RUN_ID        VARCHAR,
  SOURCE_FQN    VARCHAR,
  TARGET_FQN    VARCHAR,
  RULE_ID       VARCHAR,
  TITLE         VARCHAR,
  EXPLANATION   VARCHAR,
  RISK          VARCHAR,
  FIX_SQL       VARCHAR,
  GENERATED_BY  VARCHAR,
  STATUS        VARCHAR,
  ROWS_AFFECTED NUMBER,
  CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  DECIDED_AT    TIMESTAMP_NTZ,
  DECIDED_BY    VARCHAR
);

CREATE TABLE IF NOT EXISTS DQ_GUARDIAN.DQ.FIX_AUDIT_LOG (
  AUDIT_ID          VARCHAR,
  PROPOSAL_ID       VARCHAR,
  TARGET_FQN        VARCHAR,
  ACTION            VARCHAR,
  SQL_TEXT          VARCHAR,
  ROWS_AFFECTED     NUMBER,
  ROW_COUNT_BEFORE  NUMBER,
  ROW_COUNT_AFTER   NUMBER,
  MESSAGE           VARCHAR,
  ACTOR             VARCHAR,
  ACTOR_ROLE        VARCHAR,
  EVENT_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW DQ_GUARDIAN.DQ.V_LATEST_SCANS AS
SELECT * FROM DQ_GUARDIAN.DQ.SCAN_RUNS
QUALIFY ROW_NUMBER() OVER (PARTITION BY TARGET_FQN ORDER BY RUN_TS DESC) = 1;

CREATE OR REPLACE VIEW DQ_GUARDIAN.DQ.V_OPEN_ISSUES AS
SELECT s.TARGET_FQN, r.SEVERITY, r.DIMENSION, r.RULE_TYPE, r.COLUMN_NAME,
       r.FAILED_ROWS, r.TOTAL_ROWS, ROUND(100 - r.PASS_PCT, 2) AS FAIL_PCT, r.DESCRIPTION
FROM DQ_GUARDIAN.DQ.SCAN_RESULTS r
JOIN DQ_GUARDIAN.DQ.V_LATEST_SCANS s ON s.RUN_ID = r.RUN_ID
WHERE r.STATUS = 'FAIL';

CREATE OR REPLACE TABLE DQ_GUARDIAN.RAW.CUSTOMERS AS
WITH g AS (
  SELECT SEQ4() + 1 AS N FROM TABLE(GENERATOR(ROWCOUNT => 5000))
),
b AS (
  SELECT
    N,
    GET(ARRAY_CONSTRUCT('Aarav','Vivaan','Aditya','Vihaan','Arjun','Sai','Reyansh','Ayaan','Krishna','Ishaan',
                        'Ananya','Diya','Aadhya','Saanvi','Kavya','Riya','Meera','Priya','Sneha','Ishita'),
        MOD(ABS(HASH(N, 'fn')), 20))::STRING AS FNAME,
    GET(ARRAY_CONSTRUCT('Sharma','Patel','Mohanty','Das','Nayak','Reddy','Iyer','Singh','Kumar','Mishra',
                        'Panda','Behera','Rao','Gupta','Joshi'),
        MOD(ABS(HASH(N, 'ln')), 15))::STRING AS LNAME,
    MOD(ABS(HASH(N, 'city')), 10) AS CI,
    GET(ARRAY_CONSTRUCT('Bhubaneswar','Cuttack','Mumbai','Pune','Bengaluru','Chennai','Hyderabad','Kolkata','Delhi','Jaipur'),
        MOD(ABS(HASH(N, 'city')), 10))::STRING AS CITY0,
    GET(ARRAY_CONSTRUCT('Odisha','Odisha','Maharashtra','Maharashtra','Karnataka','Tamil Nadu','Telangana','West Bengal','Delhi','Rajasthan'),
        MOD(ABS(HASH(N, 'city')), 10))::STRING AS STATE0,
    '9' || LPAD(MOD(ABS(HASH(N, 'ph')), 1000000000)::STRING, 9, '0') AS PHONE0,
    (1 + MOD(ABS(HASH(N, 'pin1')), 8))::STRING || LPAD(MOD(ABS(HASH(N, 'pin2')), 100000)::STRING, 5, '0') AS PIN0,
    DATEADD(day, -(7300 + MOD(ABS(HASH(N, 'dob')), 16000)), CURRENT_DATE()) AS DOB0,
    GET(ARRAY_CONSTRUCT('Gold','Silver','Bronze'), MOD(ABS(HASH(N, 'tier')), 3))::STRING AS TIER0
  FROM g
)
SELECT
  N AS CUSTOMER_ID,
  FNAME AS FIRST_NAME,
  LNAME AS LAST_NAME,
  CASE WHEN MOD(N, 37) = 0 THEN NULL
       WHEN MOD(N, 41) = 0 THEN LOWER(FNAME) || N || 'example.com'
       WHEN MOD(N, 53) = 0 THEN '  ' || LOWER(FNAME) || '.' || LOWER(LNAME) || N || '@example.com'
       ELSE LOWER(FNAME) || '.' || LOWER(LNAME) || N || '@example.com' END AS EMAIL,
  CASE WHEN MOD(N, 43) = 0 THEN NULL
       WHEN MOD(N, 61) = 0 THEN LPAD(MOD(ABS(HASH(N, 'sh')), 10000000)::STRING, 7, '0')
       WHEN MOD(N, 29) = 0 THEN '+91-' || PHONE0
       WHEN MOD(N, 67) = 0 THEN SUBSTR(PHONE0, 1, 5) || ' ' || SUBSTR(PHONE0, 6)
       ELSE PHONE0 END AS PHONE,
  CASE WHEN MOD(N, 173) = 0 THEN NULL
       WHEN MOD(N, 211) = 0 THEN DATEADD(year, 3, CURRENT_DATE())
       WHEN MOD(N, 307) = 0 THEN DATE '1850-01-01'
       ELSE DOB0 END AS DATE_OF_BIRTH,
  CITY0 AS CITY,
  CASE WHEN MOD(N, 19) = 0 THEN UPPER(STATE0)
       WHEN MOD(N, 23) = 0 THEN LOWER(STATE0)
       WHEN MOD(N, 89) = 0 THEN SUBSTR(STATE0, 1, 2) || SUBSTR(STATE0, 4)
       ELSE STATE0 END AS STATE,
  CASE WHEN MOD(N, 97) = 0 THEN 'IND'
       WHEN MOD(N, 101) = 0 THEN 'india'
       WHEN MOD(N, 127) = 0 THEN 'INDIA'
       ELSE 'India' END AS COUNTRY,
  CASE WHEN MOD(N, 59) = 0 THEN NULL
       WHEN MOD(N, 71) = 0 THEN LPAD(MOD(ABS(HASH(N, 'pin2')), 100000)::STRING, 5, '0')
       WHEN MOD(N, 83) = 0 THEN 'ABC' || LPAD(MOD(ABS(HASH(N, 'pin2')), 1000)::STRING, 3, '0')
       ELSE PIN0 END AS PINCODE,
  CASE WHEN MOD(N, 199) = 0 THEN DATEADD(day, 10, CURRENT_DATE())
       WHEN MOD(N, 251) = 0 THEN DATEADD(year, 5, DOB0)
       ELSE DATEADD(day, -(1 + MOD(ABS(HASH(N, 'su')), 1500)), CURRENT_DATE()) END AS SIGNUP_DATE,
  CASE WHEN MOD(N, 103) = 0 THEN LOWER(TIER0)
       WHEN MOD(N, 149) = 0 THEN SUBSTR(TIER0, 1, 3) || SUBSTR(TIER0, 5)
       ELSE TIER0 END AS CUSTOMER_TIER,
  (CASE WHEN MOD(N, 97) = 0 THEN -5000
        WHEN MOD(N, 277) = 0 THEN 9999999
        ELSE 10000 + MOD(ABS(HASH(N, 'cl')), 90) * 1000 END)::NUMBER(12,0) AS CREDIT_LIMIT
FROM b;

INSERT INTO DQ_GUARDIAN.RAW.CUSTOMERS
SELECT * FROM DQ_GUARDIAN.RAW.CUSTOMERS WHERE MOD(CUSTOMER_ID, 50) = 0;

CREATE OR REPLACE TABLE DQ_GUARDIAN.RAW.ORDERS AS
WITH g AS (
  SELECT SEQ4() + 1 AS N FROM TABLE(GENERATOR(ROWCOUNT => 12000))
),
b AS (
  SELECT
    N,
    1 + MOD(ABS(HASH(N, 'cust')), 5000) AS CUST0,
    DATEADD(day, -(8 + MOD(ABS(HASH(N, 'od')), 720)), CURRENT_DATE()) AS OD0,
    GET(ARRAY_CONSTRUCT('Electronics','Grocery','Fashion','Home','Books','Sports'), MOD(ABS(HASH(N, 'cat')), 6))::STRING AS CAT0,
    1 + MOD(ABS(HASH(N, 'q')), 10) AS Q0,
    ROUND(100 + MOD(ABS(HASH(N, 'p')), 90000) / 100.0, 2) AS P0,
    GET(ARRAY_CONSTRUCT('Delivered','Shipped','Processing','Cancelled','Returned'), MOD(ABS(HASH(N, 'st')), 5))::STRING AS STATUS0
  FROM g
),
c AS (
  SELECT
    N,
    CASE WHEN MOD(N, 127) = 0 THEN 900000 + N ELSE CUST0 END AS CUSTOMER_ID,
    CASE WHEN MOD(N, 241) = 0 THEN DATEADD(day, 30, CURRENT_DATE()) ELSE OD0 END AS ORDER_DATE,
    CAT0,
    CASE WHEN MOD(N, 113) = 0 THEN -Q0 ELSE Q0 END AS QTY,
    CASE WHEN MOD(N, 283) = 0 THEN ROUND(P0 * 100, 2) ELSE P0 END AS PRICE,
    STATUS0,
    OD0
  FROM b
)
SELECT
  N AS ORDER_ID,
  CUSTOMER_ID,
  ORDER_DATE,
  CAT0 AS PRODUCT_CATEGORY,
  QTY AS QUANTITY,
  CASE WHEN MOD(N, 157) = 0 THEN NULL ELSE PRICE END AS UNIT_PRICE,
  CASE WHEN MOD(N, 91) = 0 AND MOD(N, 113) <> 0 AND MOD(N, 283) <> 0
       THEN ROUND(QTY * PRICE, 2) + 10 + MOD(N, 40)
       ELSE ROUND(QTY * PRICE, 2) END AS TOTAL_AMOUNT,
  CASE WHEN MOD(N, 137) = 0 THEN DATEADD(day, -3, ORDER_DATE)
       ELSE DATEADD(day, 1 + MOD(ABS(HASH(N, 'sd')), 7), OD0) END AS SHIP_DATE,
  CASE WHEN MOD(N, 101) = 0 THEN UPPER(STATUS0)
       WHEN MOD(N, 139) = 0 THEN SUBSTR(STATUS0, 1, 3) || SUBSTR(STATUS0, 5)
       ELSE STATUS0 END AS ORDER_STATUS
FROM c;

DELETE FROM DQ_GUARDIAN.DQ.RULES WHERE SOURCE = 'MANUAL' AND TABLE_FQN IN
  ('DQ_GUARDIAN.RAW.CUSTOMERS', 'DQ_GUARDIAN.RAW.ORDERS');

INSERT INTO DQ_GUARDIAN.DQ.RULES
  (RULE_ID, TABLE_FQN, RULE_TYPE, DIMENSION, KIND, COLUMN_NAME, EXPRESSION, PARAMS, SEVERITY, DESCRIPTION, FIX_TEMPLATE, SOURCE, ACTIVE)
SELECT 'CUSTOMERS:CUSTOM:SIGNUP_BEFORE_18', 'DQ_GUARDIAN.RAW.CUSTOMERS', 'CUSTOM', 'VALIDITY', 'ROW', 'SIGNUP_DATE',
       '"SIGNUP_DATE" < DATEADD(year, 18, "DATE_OF_BIRTH")', '{}', 'MEDIUM',
       'Customer must be at least 18 years old at sign-up', NULL, 'MANUAL', TRUE
UNION ALL
SELECT 'ORDERS:CUSTOM:TOTAL_MISMATCH', 'DQ_GUARDIAN.RAW.ORDERS', 'CUSTOM', 'ACCURACY', 'ROW', 'TOTAL_AMOUNT',
       '"TOTAL_AMOUNT" <> ROUND("QUANTITY" * "UNIT_PRICE", 2)', '{}', 'HIGH',
       'TOTAL_AMOUNT must equal QUANTITY x UNIT_PRICE',
       'UPDATE {T} SET "TOTAL_AMOUNT" = ROUND("QUANTITY" * "UNIT_PRICE", 2) WHERE "TOTAL_AMOUNT" <> ROUND("QUANTITY" * "UNIT_PRICE", 2)',
       'MANUAL', TRUE
UNION ALL
SELECT 'ORDERS:CUSTOM:SHIP_BEFORE_ORDER', 'DQ_GUARDIAN.RAW.ORDERS', 'CUSTOM', 'VALIDITY', 'ROW', 'SHIP_DATE',
       '"SHIP_DATE" < "ORDER_DATE"', '{}', 'MEDIUM',
       'Ship date cannot be earlier than order date', NULL, 'MANUAL', TRUE;

SELECT 'CUSTOMERS' AS TBL, COUNT(*) AS ROW_COUNT, COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_IDS FROM DQ_GUARDIAN.RAW.CUSTOMERS
UNION ALL
SELECT 'ORDERS', COUNT(*), COUNT(DISTINCT ORDER_ID) FROM DQ_GUARDIAN.RAW.ORDERS;

SELECT * FROM DQ_GUARDIAN.RAW.CUSTOMERS WHERE EMAIL IS NULL OR PHONE LIKE '+91%' LIMIT 10;
